server:
  port: ${PORT}

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${SPRING_CLOUD_CLIENT_IP_ADDRESS}
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

vnpay:
  tmn-code: ${VNP_TMN_CODE}
  hash-secret: ${VNP_HASH_SECRET}
  url: ${VNP_URL}

  return-url: ${VNP_RETURN_URL}
  version: "2.1.0"
  command: "pay"